services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    env_file:
      - .env.production
    volumes:
      - 'mongo:/data/db'

  lelasbot:
    build:
      context: .
    ports:
      - '443:443'
    env_file: 
      - .env.production

volumes:
  mongo: